# Generated by Django 5.0.4 on 2024-04-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
