# Generated by Django 5.0.4 on 2024-04-23 22:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_alter_machine_time_alter_productionlog_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionlog',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productionlog',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
