# Generated by Django 5.0.4 on 2024-04-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_alter_productionlog_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionlog',
            name='actual_output',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionlog',
            name='good_product',
            field=models.IntegerField(default=0),
        ),
    ]
